[package]
name = "hox"
version = "1.0.0"
authors = ["Mathias Panzenböck <grosser.meister.morti@gmx.net>"]
edition = "2018"

[dependencies]
clap = "2.33.3"
libc = "0.2.85"
pancurses-result = { version = "0.5.1", features = ["wide"] }
